[versions]
agp = "9.2.1"
ksp = "2.3.6"
aproc = "2.0.0"
hiddenapi-refine = "4.4.0"

[libraries]
hiddenapi-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "hiddenapi-refine" }
hiddenapi-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "hiddenapi-refine" }
hiddenapi-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenapi-refine" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aproc = { id = "xyz.mufanc.aproc", version.ref = "aproc" }
hiddenapi-refine = { id = "dev.rikka.tools.refine", version.ref = "hiddenapi-refine" }
